# config/routes.yml

# Default

login:
    path: /login
    defaults: { _controller: 'Runalyze\HomeController::loginAction' }
    
logout:
    path: /logout
    defaults: { _controller: 'Runalyze\HomeController::logoutAction' }
    
help:
    path: /help
    defaults: { _controller: 'Runalyze\HomeController::helpAction' }
    
register:
    path: /register
    defaults: { _controller: 'Runalyze\HomeController::registerAction' }
    
forgotpw:
    path: /forgotpw
    defaults: { _controller: 'Runalyze\HomeController::forgotPwAction' }
    
# Account activation, Deletion, Forgot password
useractivate:
    path: /activate/{hash}
    defaults: { _controller: 'Runalyze\HomeController::activateAction' }
    
userdelete:
    path: /delete/{hash}
    defaults: { _controller: 'Runalyze\HomeController::deleteAction' }
    
userforgotpw:
    path: /changepassword/{hash}
    defaults: { _controller: 'Runalyze\HomeController::changePasswordAction' }
 
default:
    path: /
    defaults: { _controller: 'Runalyze\HomeController::appAction' }
site:
    path: /{sitename}
    defaults: { _controller: 'Runalyze\HomeController::SiteAction' }
